### ISSUE TITLE
NoneType object has no attribute 'hex'

### ISSUE THREAD

**Issue by Segfaultd** [mrexodia/ida-pro-mcp#26]
### Introduction

When I ask a question in Cursor chat with all the setup done properly, the plugin in IDA is crashing and I see this in the IDA PRO console:

>   bytes   pages size description
> --------- ----- ---- --------------------------------------------
> 134217728 16384 8192 allocating memory for b-tree...
> 268435456 32768 8192 allocating memory for virtual array...
>    262144    32 8192 allocating memory for name pointers...
> -----------------------------------------------------------------
> 402915328            total memory allocated
> 
> Loading processor module E:\Reverse Engineering\IDA_Pro_8.3\procs\pc64.dll for metapc...Initializing processor module metapc...OK
> Loading type libraries...
> Autoanalysis subsystem has been initialized.
> Database for file 'Game_Exe' has been loaded.
> Hex-Rays Decompiler plugin has been loaded (v8.3.0.230608)
>   The hotkeys are F5: decompile, Ctrl-F5: decompile all.
> 
>   Please check the Edit/Plugins menu for more information.
> Hex-rays version 8.3.0.230608 has been detected, gooMBA plugin ready to use
> [MCP] Plugin loaded, use Edit -> Plugins -> MCP (Ctrl+Alt+M) to start the server
> OBJC: Identified Objective-C runtime version >= 2.0
> OBJC: warning: failed to get offset of __objc2_ivar.offs
> 101C52E40: restored microcode from idb
> 101C52E40: restored pseudocode from idb
> 103379700: restored microcode from idb
> 103379700: restored pseudocode from idb
> 103379700: using guessed type char var_40[16];
> ---------------------------------------------------------------------------------------------
> Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] 
> IDAPython 64-bit v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
> ---------------------------------------------------------------------------------------------
> [MCP] Server started at http://localhost:13337
> Traceback (most recent call last):
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 133, in do_POST
>     result = rpc_registry.dispatch(request["method"], request.get("params", []))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 51, in dispatch
>     return func(*converted_params)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 358, in wrapper
>     return sync_wrapper(ff, idaapi.MFF_READ)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 332, in sync_wrapper
>     raise res
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 322, in runned
>     res_container.put(ff())
>                       ^^^^
>   File "C:/Users/SuperReverser/AppData/Roaming/Hex-Rays/IDA Pro/plugins/mcp-plugin.py", line 415, in get_metadata
>     "sha256": ida_nalt.retrieve_input_file_sha256().hex(),
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'hex'

**Comment by Segfaultd** [comment]
As a side note: i'm currently reversing a mac-based binary. I don't have this issue happening when I reverse a Windows one.

**Comment by mrexodia** [comment]
Hm that is quite weird. It looks like it happens in the following code:

https://github.com/mrexodia/ida-pro-mcp/blob/47be91c303151255ed28473ac9453b199ab80079/src/ida_pro_mcp/mcp-plugin.py#L405-L418

Could you try to run the following commands after loading a binary in IDA?

```
import ida_nalt
print(ida_nalt.retrieve_input_file_sha256())
```

The error suggests this function returns `None`, which seems strange. As a workaround I can just check for `None`, but this command works fine on my IDA 8.3.

**Comment by Segfaultd** [comment]
Here you go :-)

```
Python>import ida_nalt
print(ida_nalt.retrieve_input_file_sha256())
None
```

**Comment by williballenthin** [comment]
(just guessing) I wonder if the input file is a fat mach-o binary, and you're reversing one of the subfiles, and IDA has a bug computing the SHA256 for the fat binary.

**Comment by mrexodia** [comment]
Time for another bug report! But yeah I will add a check for `None` and gracefully handle it!
